name: Test
"on":
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 18
          - 20
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Use Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
          cache: npm
      - name: Install
        run: npm ci
      - name: Test
        run: npm test --ignore-scripts
  test:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: test_matrix
    steps:
      - run: exit 1
        if: ${{ needs.test_matrix.result != 'success' }}
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - run: npm ci
      - run: npm run lint
